export const meta = {
  name: 'onepager-verify',
  description: 'Adversarially verify a research one-pager: list the largest assumptions with their per-share sensitivity, refute each twice, reproduce the waterfall in a standalone harness, and run a completeness critic against the research pack',
  phases: [{ title: 'Assumptions', detail: 'rank by $/share' }, { title: 'Refute', detail: 'two independent refuters per assumption' }, { title: 'Harness', detail: 'reproduce the page in node' }, { title: 'Critic', detail: 'what is still missing' }],
}
const { tk } = args
const REPO = '/Users/richardshaer/GPU Cloud and Colo Tracker'
const PACK = `/Users/richardshaer/Research/${tk}/${tk}.json`
const ASSUMPTIONS = { type:'object', required:['assumptions'], properties:{ assumptions:{ type:'array', items:{ type:'object', required:['key','claim','where','perShare'], properties:{ key:{type:'string'}, claim:{type:'string'}, where:{type:'string'}, perShare:{type:'string'} } } } } }
const VERDICT = { type:'object', required:['refuted','confidence','reason','corrected_value','source_url','quote'], properties:{ refuted:{type:'boolean'}, confidence:{type:'string', enum:['high','medium','low']}, reason:{type:'string'}, corrected_value:{type:'string'}, source_url:{type:'string'}, quote:{type:'string'} } }
const HARNESS = { type:'object', required:['reproduces','issues','verdict'], properties:{ reproduces:{type:'boolean'}, issues:{type:'array', items:{type:'object', required:['severity','description','fix'], properties:{severity:{type:'string', enum:['blocker','material','minor']}, description:{type:'string'}, fix:{type:'string'}}}}, verdict:{type:'string'} } }
const CRITIC = { type:'object', required:['missing','unsourced','next'], properties:{ missing:{type:'array', items:{type:'string'}}, unsourced:{type:'array', items:{type:'string'}}, next:{type:'array', items:{type:'string'}} } }
const common = `Today's date is in the page header. Files: the generated page ${REPO}/${tk.toLowerCase()}.html; its inputs are the 'page' and 'ramp' blocks of the ${tk} record in ${REPO}/data.json; the generator ${REPO}/onepager.js (run: cd "${REPO}" && node onepager.js ${tk} --check, and --sens for the standard sensitivities); shared ramp math ${REPO}/ramp-core.js; the research pack ${PACK} and any owner exports in /Users/richardshaer/Research/${tk}/. The spec's honest-base rules are in ${REPO}/AI-Infra-Tracker-Spec.md §6e. Use ToolSearch to load WebFetch/WebSearch for filings (SEC EDGAR, company IR). Quote code lines and filing text; never accept a number without a source.`
phase('Assumptions')
const A = await agent(`${common}\nList the ten assumptions in this page that move the per-share value most. For each: a one-line claim as the page makes it, where it sits (data.json path or page section), and the per-share effect of the honest alternative (use --sens where it covers it; otherwise estimate from the waterfall and say so). Rank by absolute effect.`, { label:`assumptions:${tk}`, phase:'Assumptions', schema:ASSUMPTIONS, effort:'xhigh' })
phase('Refute')
const votes = await parallel((A ? A.assumptions : []).flatMap(a => [0,1].map(v => () => agent(`${common}\nCLAIM under test (${a.key}): "${a.claim}" — sits at ${a.where}; the page's own sensitivity: ${a.perShare}. ${v ? 'Approach from first principles and the filings before reading the page code.' : 'Start from the page code and inputs, then the filings.'} Try to REFUTE the claim: find the primary source that contradicts or supersedes it, or the arithmetic slip. Default to refuted=true if uncertain. corrected_value = what the input should be, with the $/share effect.`, { label:`refute:${tk}:${a.key}:${v+1}`, phase:'Refute', schema:VERDICT, effort:'xhigh' }))))
phase('Harness')
const H = await agent(`${common}\nAdversarial reviewer. Port the page's quarterly cash waterfall and tie-out to a standalone node script in the session scratchpad from the page source alone (do not import onepager-core.js), run it, and compare every quarter's debt, cash, net debt, prepayments owed, shares and the final per-share value with --check. Report any divergence, any place the page's waterfall contradicts the spec §6e honest-base rules, and any typed constant that should come from the table.`, { label:`harness:${tk}`, phase:'Harness', schema:HARNESS, effort:'xhigh' })
phase('Critic')
const C = await agent(`${common}\nCompleteness critic. Read the page, its data.json blocks and the research pack. List: source types never read (last call transcript, latest 10-Q/6-K, contract exhibits, credit agreements, SemiAnalysis, construction trackers); page numbers with no dated source; assumptions resting on one secondary source; sections thinner than the IREN reference page (${REPO}/iren.html). Then the next five actions, most valuable first.`, { label:`critic:${tk}`, phase:'Critic', schema:CRITIC, effort:'high' })
const out = (A ? A.assumptions : []).map((a, i) => ({ ...a, votes: [votes[2*i], votes[2*i+1]] }))
return { assumptions: out, harness: H, critic: C }
