export const meta = {
  name: 'research-pack',
  description: 'Sweep filings, calls, decks and trusted secondary sources for one AI-infrastructure name, refute every strand, consolidate into a sourced research pack, then close the gaps',
  phases: [{ title: 'Sweep', detail: 'one agent per source strand' }, { title: 'Refute', detail: 'independent refuter per strand' }, { title: 'Consolidate', detail: 'merge into packs/<tk>.json' }, { title: 'Gaps', detail: 'critic, then a second sweep on what is missing' }],
}
const { tk, name, model, hints } = args
const OUT = args.out || '/Users/richardshaer/Research/' + args.tk
const FACTS = { type:'object', required:['facts','notes','sources'], properties:{
  facts:{ type:'array', items:{ type:'object', required:['topic','claim','value','asOf','source_url','quote','confidence','tier'], properties:{
    topic:{type:'string'}, claim:{type:'string'}, value:{type:'string'}, unit:{type:'string'}, asOf:{type:'string'}, source_url:{type:'string'}, quote:{type:'string'},
    confidence:{type:'string', enum:['high','medium','low']}, tier:{type:'string', enum:['filing','company','transcript','trusted-secondary','press','derived']} } } },
  notes:{type:'string'}, sources:{type:'array', items:{type:'string'}} } }
const VERDICT = { type:'object', required:['refuted','reason','corrections'], properties:{ refuted:{type:'boolean'}, reason:{type:'string'}, corrections:{type:'array', items:{type:'object', required:['claim','correct_value','source_url','quote'], properties:{claim:{type:'string'}, correct_value:{type:'string'}, source_url:{type:'string'}, quote:{type:'string'}}}} } }
const PACK = { type:'object', required:['path','counts','gaps','summary'], properties:{ path:{type:'string'}, counts:{type:'object', additionalProperties:{type:'number'}}, gaps:{type:'array', items:{type:'string'}}, summary:{type:'string'} } }
const GAPS = { type:'object', required:['missing','queries'], properties:{ missing:{type:'array', items:{type:'string'}}, queries:{type:'array', items:{type:'object', required:['key','prompt'], properties:{key:{type:'string'}, prompt:{type:'string'}}}} } }
const common = `Today is 2026-09-04. Company: ${name} (${tk}). Business model: ${model}. ${hints}
Use ToolSearch to load WebFetch and WebSearch first. Source hierarchy: (1) SEC EDGAR filings and exhibits (find the CIK on EDGAR; 10-K/10-Q/8-K/S-1/424B or 20-F/6-K; contracts and credit agreements filed as exhibits), (2) the company's own press releases, investor decks and earnings-call transcripts (company IR site; fool.com / stockanalysis.com transcripts are acceptable when the company does not post one), (3) trusted secondary: SemiAnalysis public posts, TrendForce, Dell'Oro, construction/satellite trackers on X or Substack, named Substack analysts; (4) press (Reuters, Bloomberg, The Information, Data Center Dynamics) only to locate a primary. Sell-side notes may be used for FACTS they cite, never for targets or ratings.
Rules: every fact carries an as-of date, the exact quote and the URL. Never infer a number that is not in a document; if you must compute one, tier it 'derived' and show the arithmetic in the claim. Prefer the latest filing over older ones and say when a number superseded an earlier one. Cover the whole history since the company's AI-infrastructure pivot, not just the latest quarter. Return raw facts, not narrative.`
const STRANDS = [
  { key:'capacity', prompt:`${common}\nSTRAND: sites and capacity. Every data-centre site: name, location, lessor or owned, gross MW, IT/critical MW, energisation or commissioning date (state whether disclosed, guided or estimated), status today, GPU generation deployed or planned, the customer if disclosed. The company's own capacity metrics by quarter since 2024 (e.g. active power, contracted power, connected MW, GPUs online) and every forward guidance number for 2026-2030 (GW by year-end) with the date it was given and whether it was later revised.` },
  { key:'contracts', prompt:`${common}\nSTRAND: customer contracts and backlog. Every disclosed contract: customer, total contract value, term, start date, MW or GPU count, implied $ per MW-year or $ per GPU-hour (derived, show arithmetic), prepayment percentage and mechanics (when paid, how credited back), take-or-pay, renewal/expansion options. Backlog / RPO / ARR by quarter since 2024 and the company's exact definition of each metric, including what is excluded (options, unsigned, spot).` },
  { key:'financials', prompt:`${common}\nSTRAND: reported financials. By quarter since Q1-2024: revenue (by segment if disclosed), adjusted EBITDA and margin, GAAP operating income, D&A, interest expense, net income, cash capex, purchases of property and equipment, deferred revenue / customer prepayments received, cash, restricted cash, total debt, basic and diluted share count. Year-end 2025 and latest-quarter balance sheet in full. Consensus revenue and EBITDA by quarter and by year for 2026-2028 from at least two public aggregators (e.g. stockanalysis.com, Yahoo Finance, Koyfin public pages), with date captured.` },
  { key:'financing', prompt:`${common}\nSTRAND: financing. Every debt instrument and facility: name, size, drawn amount, rate (base + spread or fixed), OID, amortisation schedule, maturity, security/collateral, recourse, covenants (DSCR, LTV/LTC, minimum liquidity), lender, date. Every convertible note series: principal, coupon, conversion price, maturity, redemption/put dates, capped calls and their cap prices. Finance-lease and operating-lease liabilities and the underlying lease terms ($ per kW-month or $ per MW-year, term, escalators) with lessors. Customer prepayments received and outstanding. Equity raises, ATM programmes and warrants. Management statements on cost of debt and funding mix.` },
  { key:'capex', prompt:`${common}\nSTRAND: capex and unit economics. Capex per MW and per GPU by generation from disclosed orders or per-contract disclosures (show arithmetic), capex guidance by year and how it was revised, cash capex by quarter, GPU useful-life and depreciation policy and any changes, payback statements by management (and the basis: gross revenue or after direct costs), gross margin and adjusted EBITDA margin by quarter, power and lease cost per MW where disclosed, refresh/upgrade policy.` },
  { key:'pricing', prompt:`${common}\nSTRAND: market pricing. The company's own price prints ($ per GPU-hour on-demand and reserved, $ per MW-year implied by new contracts) by date; peer prints (IREN, Nebius, CoreWeave, Lambda, Crusoe, Oracle, hyperscalers) for the same SKUs (H100, H200, B200, B300/GB300, VR200/Vera Rubin); SemiAnalysis, TrendForce and other public pricing series; the direction of pricing over the last 12 months with dates. Distinguish contract tenor (1-yr, 3-yr, 5-yr) and whether prices include storage, networking and managed services.` },
  { key:'management', prompt:`${common}\nSTRAND: management commentary. From every earnings call, investor day and public conference appearance since Q1-2025: quotes (speaker, date, event) on capacity timing, capex, backlog conversion, pricing, prepayments, financing, GPU life, NVIDIA allocation, customer concentration, and any guidance later missed or changed. Include the most recent quarter's Q&A in detail. Flag every date or target that slipped, with both the original and the revised statement.` },
  { key:'secondary', prompt:`${common}\nSTRAND: trusted secondary coverage. Identify who covers this name in depth outside the sell side: SemiAnalysis (public posts and any quoted excerpts of paid work), Substack authors, X/Twitter construction trackers using satellite or ground footage, data-centre trade press, and independent analysts. For each: name, URL, what they track, and their most-cited quantitative claims about this company (site progress, MW timing, pricing, financing) with dates and quotes. Note explicitly which sources are paywalled and what they cover, so the owner can decide what to export.` },
  { key:'risks', prompt:`${common}\nSTRAND: risks and the share count. Customer concentration by revenue and backlog; lessor and supplier dependencies; litigation, short reports and regulatory matters; delays and their causes; covenant pressure; going-concern or liquidity language. The full dilution picture: basic shares, RSUs and options outstanding, warrants (e.g. NVIDIA or AMD warrants), convertible notes if-converted shares, ATM capacity, lock-ups, share classes and voting control, insider selling.` },
]
phase('Sweep')
const swept = await parallel(STRANDS.map(s => () => agent(s.prompt, { label:`sweep:${tk}:${s.key}`, phase:'Sweep', schema:FACTS, effort:'high' })))
phase('Refute')
const refuted = await parallel(STRANDS.map((s, i) => () => {
  const r = swept[i]; if (!r) return Promise.resolve(null)
  return agent(`${common}\nYou are an independent refuter for the strand '${s.key}'. Claims:\n${JSON.stringify(r.facts.slice(0, 80), null, 1)}\nFetch every cited source and confirm the quote exists and supports the value; search for a later or contradicting primary source. Return refuted=true if any material claim is wrong, stale or unsupported, and list every correction with the right value, URL and quote.`, { label:`refute:${tk}:${s.key}`, phase:'Refute', schema:VERDICT, effort:'high' })
}))
phase('Consolidate')
const consolidate = (round, extraFacts) => agent(`${common}\nYou are the consolidator. Merge the following sweep results and refuter corrections into ONE research pack JSON file at ${OUT}/${tk}.json (create the directory if needed). Structure: {tk, name, asOf, model, sites:[...], capacityByQuarter:[...], guidance:[...], contracts:[...], backlogByQuarter:[...], financialsByQuarter:[...], consensus:[...], balanceSheet:{...}, debt:[...], converts:[...], leases:[...], prepayments:{...}, capex:{...}, unitEconomics:{...}, pricing:[...], management:[...], secondary:[...], risks:[...], dilution:{...}, sourcesIndex:[...]}. Every leaf number keeps its asOf, source_url and quote (use {v, asOf, src, q} objects). Apply corrections over the original claims; when two sources disagree keep both with a 'conflict' note. ${round > 1 ? 'A pack already exists at that path: read it and merge the new facts into it, do not drop anything.' : ''} Then return the path, counts per section, the list of gaps you can see (metrics with no number, quarters missing, instruments without terms, sites without dates) and a 300-word summary.\nSWEEP RESULTS:\n${JSON.stringify(extraFacts).slice(0, 350000)}`, { label:`consolidate:${tk}:r${round}`, phase:'Consolidate', schema:PACK, effort:'high' })
let pack = await consolidate(1, { strands: STRANDS.map((s,i)=>({ key:s.key, facts:swept[i]?swept[i].facts:[], notes:swept[i]?swept[i].notes:'', corrections:refuted[i]?refuted[i].corrections:[], refuted:refuted[i]?refuted[i].refuted:null })) })
log(`${tk} pack round 1: ${pack ? pack.summary.slice(0,200) : 'no pack'}`)
phase('Gaps')
for (let round = 2; round <= 3 && pack; round++) {
  const gaps = await agent(`${common}\nYou are the completeness critic. Read the research pack at ${pack.path}. List what a first-principles per-MW valuation page still cannot be built from it: missing quarters, sites without dates or MW, contracts without $/MW, debt without amortisation or covenants, no consensus, no useful-life policy, no lease cost per MW, no prepayment mechanics, no capped-call terms, unread source types (e.g. no S-1 read, no exhibit read, no transcript of the last call, no SemiAnalysis piece). Also list claims that rest on a single secondary source. Then write up to 6 targeted search prompts, each self-contained, to close the biggest gaps. If the pack is complete enough, return an empty queries list.`, { label:`gaps:${tk}:r${round}`, phase:'Gaps', schema:GAPS, effort:'high' })
  if (!gaps || !gaps.queries.length) { log(`${tk}: critic found nothing worth another round`); break }
  log(`${tk} round ${round}: ${gaps.queries.length} gap queries — ${gaps.missing.slice(0,5).join('; ')}`)
  const more = await parallel(gaps.queries.map(q => () => agent(`${common}\nGAP QUERY (${q.key}): ${q.prompt}`, { label:`gap:${tk}:${q.key}`, phase:'Gaps', schema:FACTS, effort:'high' })))
  const moreRef = await parallel(gaps.queries.map((q, i) => () => { const r = more[i]; if (!r) return Promise.resolve(null)
    return agent(`${common}\nIndependent refuter for gap strand '${q.key}'. Claims:\n${JSON.stringify(r.facts.slice(0,60), null, 1)}\nFetch every cited source, confirm quotes, search for contradicting or later primary sources; refuted=true if any material claim fails; list corrections.`, { label:`refute-gap:${tk}:${q.key}`, phase:'Gaps', schema:VERDICT, effort:'high' }) }))
  pack = await consolidate(round, { strands: gaps.queries.map((q,i)=>({ key:q.key, facts:more[i]?more[i].facts:[], notes:more[i]?more[i].notes:'', corrections:moreRef[i]?moreRef[i].corrections:[], refuted:moreRef[i]?moreRef[i].refuted:null })) })
}
return pack